import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Wibutime :: Home",
  description: "Generated by create next app",
};

export default function HomeLayout({
  top_user,
  top_views,
  children,
}: Readonly<{
  top_user: React.ReactNode;
  top_views: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <div className="px-4 max-w-[1300px] mx-auto min-h-dvh overflow-y-auto pb-4 pt-[82px] flex flex-col gap-4 showScroll">
      {children}
      {top_views}
      {top_user}
    </div>
  );
}
