import type { Metadata } from "next";

import Header from "@/components/shared/Header/Header";

export const metadata: Metadata = {
  title: "Wibutime :: Auth",
  description: "Generated by create next app",
};

export default function NavbarLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main>{children}</main>
    </>
  );
}
