import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { SessionProvider } from "next-auth/react";

import { Toaster } from "@/components/ui/sonner";

import { auth } from "@/auth";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ProgressBarProviders from "@/components/providers/ProgressBarProvider";

const roboto = Roboto({
  subsets: ["vietnamese"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="vi" suppressHydrationWarning>
        <body className={roboto.className}>
          <ThemeProvider attribute="class" defaultTheme="system">
            <ProgressBarProviders>{children}</ProgressBarProviders>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
