import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Wibutime :: Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className="w-screen h-dvh overflow-y-auto">{children}</main>;
}
